require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MmaGymsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MmaGym. As you add validations to MmaGym, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MmaGymsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all mma_gyms as @mma_gyms" do
      mma_gym = MmaGym.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mma_gyms)).to eq([mma_gym])
    end
  end

  describe "GET #show" do
    it "assigns the requested mma_gym as @mma_gym" do
      mma_gym = MmaGym.create! valid_attributes
      get :show, {:id => mma_gym.to_param}, valid_session
      expect(assigns(:mma_gym)).to eq(mma_gym)
    end
  end

  describe "GET #new" do
    it "assigns a new mma_gym as @mma_gym" do
      get :new, {}, valid_session
      expect(assigns(:mma_gym)).to be_a_new(MmaGym)
    end
  end

  describe "GET #edit" do
    it "assigns the requested mma_gym as @mma_gym" do
      mma_gym = MmaGym.create! valid_attributes
      get :edit, {:id => mma_gym.to_param}, valid_session
      expect(assigns(:mma_gym)).to eq(mma_gym)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MmaGym" do
        expect {
          post :create, {:mma_gym => valid_attributes}, valid_session
        }.to change(MmaGym, :count).by(1)
      end

      it "assigns a newly created mma_gym as @mma_gym" do
        post :create, {:mma_gym => valid_attributes}, valid_session
        expect(assigns(:mma_gym)).to be_a(MmaGym)
        expect(assigns(:mma_gym)).to be_persisted
      end

      it "redirects to the created mma_gym" do
        post :create, {:mma_gym => valid_attributes}, valid_session
        expect(response).to redirect_to(MmaGym.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved mma_gym as @mma_gym" do
        post :create, {:mma_gym => invalid_attributes}, valid_session
        expect(assigns(:mma_gym)).to be_a_new(MmaGym)
      end

      it "re-renders the 'new' template" do
        post :create, {:mma_gym => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mma_gym" do
        mma_gym = MmaGym.create! valid_attributes
        put :update, {:id => mma_gym.to_param, :mma_gym => new_attributes}, valid_session
        mma_gym.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mma_gym as @mma_gym" do
        mma_gym = MmaGym.create! valid_attributes
        put :update, {:id => mma_gym.to_param, :mma_gym => valid_attributes}, valid_session
        expect(assigns(:mma_gym)).to eq(mma_gym)
      end

      it "redirects to the mma_gym" do
        mma_gym = MmaGym.create! valid_attributes
        put :update, {:id => mma_gym.to_param, :mma_gym => valid_attributes}, valid_session
        expect(response).to redirect_to(mma_gym)
      end
    end

    context "with invalid params" do
      it "assigns the mma_gym as @mma_gym" do
        mma_gym = MmaGym.create! valid_attributes
        put :update, {:id => mma_gym.to_param, :mma_gym => invalid_attributes}, valid_session
        expect(assigns(:mma_gym)).to eq(mma_gym)
      end

      it "re-renders the 'edit' template" do
        mma_gym = MmaGym.create! valid_attributes
        put :update, {:id => mma_gym.to_param, :mma_gym => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested mma_gym" do
      mma_gym = MmaGym.create! valid_attributes
      expect {
        delete :destroy, {:id => mma_gym.to_param}, valid_session
      }.to change(MmaGym, :count).by(-1)
    end

    it "redirects to the mma_gyms list" do
      mma_gym = MmaGym.create! valid_attributes
      delete :destroy, {:id => mma_gym.to_param}, valid_session
      expect(response).to redirect_to(mma_gyms_url)
    end
  end

end
